### ISSUE TITLE
Add readme file

### ISSUE THREAD

**Issue by anantcodes** [anantcodes/ari#1]
Please provide a descriptive readme file for this repo.
The file should contain 2 sections: brief and detailed descriptions respectively.

**Comment by risacodes** [comment]
Hi @anantcodes ,
I can resolve this issue . Please assign this to me .

**Comment by anantcodes** [comment]
Sure @risacodes.

**Comment by risacodes** [comment]
Thanks! On it.

**Comment by anantcodes** [comment]
Merged but please elaborate more on the description part.

**Comment by risacodes** [comment]
Sure.
